import type { Metadata } from 'next';
import { Do_Hyeon } from 'next/font/google';
// import { Inter } from 'next/font/google';
import './globals.css';
import ClientProvider from '@/components/ClientProvider';

// const inter = Inter({ subsets: ['latin'] });
const doHyun = Do_Hyeon({
    subsets: ['latin'],
    weight: '400',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            {/* <body className={inter.className}>{children}</body> */}
            <body className={doHyun.className}>
                <ClientProvider>{children}</ClientProvider>
            </body>
        </html>
    );
}
