import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import MenuArea from '@/components/MenuArea';
import ClientProvider from './ClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ClientProvider>
                    <div className='w-screen h-screen'>
                        <div className=''>
                            <Navbar />
                        </div>
                        <div className='flex justify-center w-full'>
                            <MenuArea></MenuArea>
                        </div>
                        <div className='flex flex-1 max-h-full'>{children}</div>
                    </div>
                </ClientProvider>
            </body>
        </html>
    );
}
