import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Counter from '@/components/Counter';
import TodoApp from '@/components/TodoApp';
import ClientProvider from '@/components/ClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ClientProvider>
                    <div className='flex m-6 gap-4'>
                        <div className='border border-blue-300 flex-1'>
                            <Counter />
                        </div>
                        <div className='border border-green-300 flex-1'>
                            <TodoApp />
                        </div>

                        {children}
                    </div>
                </ClientProvider>
            </body>
        </html>
    );
}
