import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TodoApp from '@/components/TodoApp';
import ClientProvider from '@/components/ClientProvider';
import { cn } from '@/lib/utils';
import Counter from '@/components/Counter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={cn(
                    'min-h-screen bg-background font-sans antialiased',
                    inter.className,
                )}
            >
                <ClientProvider>
                    <div className='flex m-6 gap-4'>
                        <div className=' border-green-300 flex-1'>
                            <Counter />
                        </div>
                        {/* <TodoApp /> */}

                        {children}
                    </div>
                </ClientProvider>
            </body>
        </html>
    );
}
